### ISSUE TITLE
Experiment a new hooks based API

### ISSUE THREAD

**Issue by FezVrasta** [popperjs/react-popper#241]
I'd like to add, on top of the existing render-props based API, a way to use react-popper with the new React hooks.

I can think of a possible API to look like the following:

```jsx
import { usePopper } from 'react-popper';

const Example = () => {
  const [reference, popper, arrow] = usePopper(options);

  return (
	<Fragment>
      <button type="button" ref={reference.ref}>
        Reference element
      </button>
    
      <div ref={popper.ref} style={popper.style} data-placement={popper.placement}>  
        Popper element
        <div ref={arrow.ref} style={arrow.style} />
      </div>
    </Fragment>
  );
}
```

I still have to think of a way to allow multiple poppers handled by the same reference, I think a possibility would be to expose an utility that merges `reference.ref` into a single one:

```jsx
import { usePopper, mergeRef } from 'react-popper';

const Example = () => {
  const [reference1, popper1, arrow1] = usePopper(options);
  const [reference2, popper2, arrow2] = usePopper(options);

  return (
	<Fragment>
      <button type="button" ref={mergeRef(reference1.ref, reference2.ref)}>
        Reference element
      </button>
    
      <div ref={popper1.ref} style={popper1.style} data-placement={popper1.placement}>  
        Popper element
        <div ref={arrow1.ref} style={arrow1.style} />
      </div>

      <div ref={popper2.ref} style={popper2.style} data-placement={popper2.placement}>  
        Popper element
        <div ref={arrow2.ref} style={arrow2.style} />
      </div>
    </Fragment>
  );
}
```

What do you think? Suggestions? Ideas?

**Comment by SidKH** [comment]
Looks awesome!

Merge ref utility sounds like a great solution. Should be easy to implement as well
```javascript
const mergeRef = (...refs) => (ref) => refs.forEach(fn => fn(ref))
```

Also in multiple poppers example a thing to keep in mind is that change in a state of first `usePopper` will trigger re-render of component and therefore calls second `usePopper` and vise versa but since react-popper already has checks to prevent unnecessary re-computations it should be fine.

**Comment by TrySound** [comment]
We may omit mergeRef utility with just changing refs from return values to arguments
```js
const Example = () => {
  const referenceRef = useRef(null)
  const popperRef = useRef(null)
  const arrowRef  = useRef(null)
  const [popper, arrow] = usePopper(referenceRef, popperRef, arrowRef, options);

  const { width, height } = useMeasure(referenceRef)

  return (
    <Fragment>
      <button type="button" ref={referenceRef}>
        Reference element
      </button>
    
      <div ref={popperRef} style={popper.style} data-placement={popper.placement}>  
        Popper element
        <div ref={arrowRef} style={arrow.style} />
      </div>
    </Fragment>
  );
}
```

This way referenced may be passed even from props without necessity to wrap reference with popup component.
https://github.com/Andarist/use-onclickoutside

**Comment by nassimbenkirane** [comment]
It would be great to also be able to merge the refs with external refs,
and/or to give only some refs as params:
```javascript
const popperRef=useRef();
const {popper, arrow, managerRef, arrowRef} = usePopper({popperRef});
```

**Comment by FezVrasta** [comment]
@nassimbenkirane if we are going with @TrySound suggestion I don't think we need it.

https://github.com/FezVrasta/react-popper/issues/241#issuecomment-439604034

**Comment by nassimbenkirane** [comment]
@FezVrasta, @TrySound,
You're right that if with this suggestion, we don't need to merge refs,
I think it's a good solution, I just think that providing a custom ref should be an 'opt in' behaviour, as it would make the default API a little more verbose.

I'd like to be able to provide only a subset of the refs and take the rest from the objects provided by usePopper

```javascript
const Example = () => {
  const referenceRef = useRef(null)
  const {reference, popper, arrow} = usePopper({referenceRef}, options);

  const { width, height } = useMeasure(referenceRef)

  return (
    <Fragment>
      <button type="button" ref={reference.ref}> // or referenceRef as it would point to the same object
        Reference element
      </button>
    
      <div ref={popper.ref} style={popper.style} data-placement={popper.placement}>  
        Popper element
        <div ref={arrow.ref} style={arrow.style} />
      </div>
    </Fragment>
  );
}
```
Here we only need a custom ref for the referenceRef

**Comment by nassimbenkirane** [comment]
Hi @TrySound,

I kindly disagree with you on this one 🙂,
Good APIs should be simple to use for the general use case, and easy to extend for the 1-5% cases where you need more control.

In the general use case where you want one popper and don't need to tweek with the refs yourself (as in your example with useMeasure), compare this :
```javascript
  const referenceRef = useRef(null)
  const popperRef = useRef(null)
  const arrowRef  = useRef(null)
  const [popper, arrow] = usePopper(referenceRef, popperRef, arrowRef, options);
```
to this :
```javascript
const [reference, popper, arrow] = usePopper(options);
```
In the first case, one could say usePopper leaks implementation details, and it makes it more error-prone since there is more reponsability put on the developer. The second one is just easier.

I agree it's a tradeoff though

Also I'm not found of positional arguments for usePopper,  as it would be a breaking change to add one additional argument in the future

That said, being able to provide the refs that we want to usePopper is a very good idea, and whatever the final API, I'm so excited for the hooks version !!
In our use case it will yield a massive simplification of our components 😁

**Comment by TrySound** [comment]
I'm not insist on positional arguments. It's just an example. My point only against two sources of refs.
```js
const referenceRef = useRef(null)
const popperRef = useRef(null)
const [reference, popper, arrow] = usePopper({
  referenceRef,
  popperRef,
})
// reference.ref === undefined
// popper.ref === undefined
```

**Comment by nassimbenkirane** [comment]
I get your point

**Comment by FezVrasta** [comment]
Remember that `react-popper` is meant to be a thin layer between React and Popper.js, it's not meant to be used directly, you will likely use something more user-friendly such as a tooltip library that relies on react-popper for the positioning.

So I'd prefer to keep the API verbose but powerful rather than easy to use but with gotchas to make it work in more advanced cases.

**Comment by nassimbenkirane** [comment]
@FezVrasta makes sense :)

**Comment by t3kkitz** [comment]
Instead of:
`const [reference, popper, arrow] = usePopper(options);`
I think better to use object destructuring coz remembering arguments order is 'meh':
`const {reference, popper, arrow} = usePopper(options);`
or you can use it with multiple instances with access by key
`const popup1 = usePopper(options);` 
`const popup2 = usePopper(options);`
`...`
` <div ref={popup1.ref}>elem<div>`

**Comment by FezVrasta** [comment]
I don't know how much supported this would be, but we could have an iterable object to support both cases.. lol

```js
const result = {
  reference: 'reference',
  popper: 'popper',
  arrow: 'arrow',
  [Symbol.iterator]() {
    let index = 0;
    let properties = Object.keys(this);
    let done = false;
    return {
      next: () => {
        done = index >= properties.length;
        let obj = {
          done,
          value: this[properties[index]],
          key: properties[index]
        };
        index++;
        return obj;
      }
    };
  }
};
```

![image](https://user-images.githubusercontent.com/5382443/49292187-dd59c400-f4ac-11e8-856e-c50106532d99.png)

**Comment by donysukardi** [comment]
I'd prefer for users to supply their own refs, instead of the library returning pre-created ones. Just in case they want to do something else with the refs.

Here's my take on usePopper hook - https://codesandbox.io/s/0xrj13y4n, based on the same implementation as good old react-popper.

```js
import { useCallback, useState, useEffect, useRef } from "react";
import PopperJS from "popper.js";

const defaultOpts = {
  placement: "bottom",
  eventsEnabled: true,
  referenceElement: undefined,
  positionFixed: false
};

const initialStyle = {
  position: "absolute",
  top: 0,
  left: 0,
  opacity: 0,
  pointerEvents: "none"
};

const initialArrowStyle = {};
const noop = () => {};

export default function usePopper(inputOpts) {
  const opts = { ...defaultOpts, ...inputOpts };
  const { referenceNode, popperNode, arrowNode } = opts;
  const [state, setState] = useState({
    data: undefined,
    placement: undefined
  });
  const popperInstance = useRef();

  const callbackFn = useCallback(data => {
    const { placement } = data;
    setState({ data, placement });
    return data;
  }, []);

  useEffect(
    () => {
      // A placement difference in state means popper determined a new placement
      // apart from the opts value. By the time the popper element is rendered with
      // the new position Popper has already measured it, if the place change triggers
      // a size change it will result in a misaligned popper. So we schedule an update to be sure.
      if (popperInstance.current) {
        popperInstance.current.scheduleUpdate();
      }
    },
    [state.placement]
  );

  useEffect(
    () => {
      if (referenceNode.current && popperNode.current) {
        popperInstance.current = new PopperJS(
          referenceNode.current,
          popperNode.current,
          {
            placement: opts.placement,
            eventsEnabled: opts.eventsEnabled,
            positionFixed: opts.positionFixed,
            modifiers: {
              ...opts.modifiers,
              arrow: {
                ...(opts.modifiers && opts.modifiers.arrow),
                enabled: !!arrowNode.current,
                element: arrowNode.current
              },
              applyStyle: { enabled: false },
              updateStateModifier: {
                enabled: true,
                order: 900,
                fn: callbackFn
              }
            }
          }
        );
      }

      return () => {
        if (popperInstance.current){
          popperInstance.current.destroy();
          popperInstance.current = null;
        }
      };
    },
    [
      popperNode.current,
      referenceNode.current,
      opts.positionFixed,
      opts.placement,
      opts.eventsEnabled
    ]
  );

  const style =
    !popperNode.current || !state.data
      ? initialStyle
      : {
          position: state.data.offsets.popper.position,
          ...state.data.styles
        };

  const arrowStyle =
    !arrowNode.current || !state.data
      ? initialArrowStyle
      : state.data.arrowStyles;

  return {
    style,
    placement: state.placement,
    outOfBoundaries: state.data && state.data.hide,
    scheduleUpdate: popperInstance ? popperInstance.scheduleUpdate : noop,
    arrowStyle
  };
}
```

**Comment by donysukardi** [comment]
I think it's better to let users pass in their own refs instead of letting the library create for them. This pattern promotes better composability.

As for the return value from usePopper, i'd vote for using object whenever the return value has more than two entries.

I took a stab at writing it as a hook too - https://codesandbox.io/s/0xrj13y4n

**Comment by FezVrasta** [comment]
@donysukardi that's some huge code reduction 😱

Would you mind sending a PR which replaces the current code with this one? I'm going to create a `v2` branch where we'll keep this code while we work on it and wait for the official release of hooks.

**Comment by denisborovikov** [comment]
> I took a stab at writing react-popper as a hook too - https://codesandbox.io/s/0xrj13y4n

Seems it's required to compare incoming data in callbackFn with the previous one and update state only if the data changes. Otherwise, the whole component updates due to numerous callbackFn calls (and state updates) on scroll. Not sure if useCallback works here.

**Comment by FezVrasta** [comment]
@donysukardi are you still interested in that PR or should I do it?

**Comment by oadrian2** [comment]
Any updates on this?

**Comment by FezVrasta** [comment]
I'm gonna work on it as soon I get back to Europe I guess

**Comment by sgenoud** [comment]
I played with Popper.js in hooks a little bit. They make the integration so much simpler there might not even need for a library anymore. I wrote a little thing about that https://carrots.sgenoud.com/use-popper.js-in-react/

Feel free to start from [my code](https://github.com/sgenoud/quarolib/blob/master/hooks/usePopper.js) if you want to have hooks as part of react-popper.

**Comment by EthanRutherford** [comment]
@sgenoud the last `useUpdate` in your code causes the popper to re-render infinitely.

**Comment by k15a** [comment]
You will have to use callback refs instead of `useRef` otherwise you will have the same problem react-dnd had with their experimental hooks API. You can read more about that here: https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node

**Comment by FezVrasta** [comment]
I'm working on this, I was converting the demo page and the tests, I'm not actually sure if the Hooks API helps in the react-popper case... Stuff got way more complex IMHO. 🤷‍♂️

**Comment by therealparmesh** [comment]
Check out:

https://www.npmjs.com/package/use-popper
https://github.com/sandiiarov/use-popper

This is what the company I'm at has been using for awhile. Maybe it can help with these discussions.

**Comment by denisborovikov** [comment]
As discussed above, declaring refs inside rather than accepting them as arguments don't look like a good idea.

**Comment by k15a** [comment]
Accepting them as arguments will lead to bugs so it's the only option.

**Comment by FezVrasta** [comment]
I was thinking that maybe a better approach could be:

```jsx
const [Popper, Reference, Arrow] = usePopper();
```

And then keep the render-prop API for the 3 components returned by the hook. Doing so we get rid of the annoying `Manager` wrapper but we keep the ability to easily spawn multiple poppers from a single `usePopper` call.

**Comment by therealparmesh** [comment]
@denisborovikov Hmm from what I can infer it seems like people are still split on this.

**Comment by denisborovikov** [comment]
It's not clear for me then, how to re-use the same DOM node.

**Comment by denisborovikov** [comment]
@therealparmesh  It's not clear for me then, how to re-use the same DOM node. 

@k15a check the updated code in the [message above ](https://github.com/FezVrasta/react-popper/issues/241#issuecomment-467105626). It uses useState instead of useRef but still accepts ref (state) as an argument. I believe it was updated after your comment.

**Comment by therealparmesh** [comment]
@denisborovikov How do you feel about something like https://github.com/FezVrasta/react-popper/issues/241#issuecomment-439604034? https://codesandbox.io/s/0qjk4w5v0l

**Comment by benbayard** [comment]
I just wanted to throw my opinion in that the benefits of positional arguments are numerous:

1. easier to support multiple poppers (because you don't have to rename the keys)
2. Follows the patterns in existing hooks like useState
3. needing to know the return order is alleviated with sufficient static typing. Editors that support static types won't need to worry about this at all.

**Comment by FezVrasta** [comment]
With the upcoming Popper 2, an hypothetical hook would look like this:

```js
export const usePopper = (options = {}) => {
  const referenceRef = useRef();
  const popperRef = useRef();

  const popperInstanceRef = useRef();

  useLayoutEffect(() => {
    const popperInstance = createPopper(
      referenceRef.current,
      popperRef.current,
      options
    );

    popperInstanceRef.current = popperInstance;

    return () => {
      popperInstance.destroy();
    };
  }, []);

  useEffect(() => {
    popperInstanceRef.current.setOptions(options);
    popperInstanceRef.current.update();
  }, [options]);

  return {
    reference: referenceRef,
    popper: popperRef,
  };
};
```

**Comment by therealparmesh** [comment]
@FezVrasta This looks great! One minor detail - Could we also expose [`scheduleUpdate`](https://popper.js.org/popper-documentation.html#Popper.scheduleUpdate) from the hook?

**Comment by FezVrasta** [comment]
yes of course, this is just a quick draft to show the potential of the new Popper API.

I'd also need to expose the `arrowRef` somehow.

**Comment by FezVrasta** [comment]
```
import { useLayoutEffect, useRef } from 'react';
import { createPopper } from '@popperjs/core/lib/popper.js';

export const usePopper = (options = {}) => {
  const referenceRef = useRef();
  const popperRef = useRef();
  const arrowRef = useRef();

  const popperInstanceRef = useRef();

  useLayoutEffect(() => {
    const popperInstance = createPopper(
      referenceRef.current,
      popperRef.current,
      {
        ...options,
        modifiers: [
          ...options.modifiers,
          { name: 'arrow', options: { element: arrowRef.current } },
        ]
      }
    );

    popperInstanceRef.current = popperInstance;

    return () => {
      popperInstance.destroy();
    };
  }, []);

  useLayoutEffect(() => {
    popperInstanceRef.current.setOptions(options);
    popperInstanceRef.current.update();
  }, [options]);

  return {
    reference: referenceRef,
    popper: popperRef,
    arrow: arrowRef,
    update: popperInstanceRef.current.update,
  };
};
```

Probably it will end up looking like this.

**Comment by atomiks** [comment]
[Here's a CodeSandbox demo of the hook for `rc.2`](https://codesandbox.io/s/elastic-napier-2nygy)

There are two examples:

- **Default**: import from the default path, `@popperjs/core`, to include all the modifiers available (even the ones you don't use)
- **Lite**: import from the lite path, `@popperjs/core/lib/popper-lite`, to import only the most necessary modifiers, and add modifiers as you go. See [tree-shaking in the docs](https://popper.js.org/docs/tree-shaking/) for more info.

> There's also the base path, `@popperjs/core/lib/popper-base`, which includes no modifiers at all, but I haven't put that in the demo. The usage is the same as lite, it's just missing 4 core modifiers. 

The hooks get repeated for each path, and maybe they will be in separate files to import from, i.e.

- **Default hook**: `import {usePopper} from '@popperjs/react';`
- **Lite hook**: `import {usePopper} from '@popperjs/react/lite';`

unless there is a better way

**Comment by FezVrasta** [comment]
I was considering adding an option to pass a custom `createPopper` function, so that consumers can override the default one with one configured with their needs.

**Comment by atomiks** [comment]
That does make sense, dependency-injectiony type of thing. How can there be a default one though? I don't think we can import from anywhere since it will add unnecessary code if they don't use that import path. It seems like it would be required to inject a `createPopper` function where the user chooses the path.

**Comment by FezVrasta** [comment]
I suppose tree-shaking should be able to strip out the default `createPopper` if it ends up unused, but I need to verify it.

**Comment by TrySound** [comment]
@FezVrasta Treeshaking will work if you will add annotation
```
const createPopper = /*#__PURE__*/popupGenerator()
```

**Comment by atomiks** [comment]
[Example of injection technique](https://codesandbox.io/s/quirky-star-vxlbm) - where would the annotation go @TrySound?

**Comment by FezVrasta** [comment]
Is `/*#__PURE__*/` necessary if the library defines `sideEffects: false` in its `package.json`?

**Comment by FezVrasta** [comment]
I'm thinking about something like this...
https://codesandbox.io/s/recursing-northcutt-porqh

```js
  const referenceRef = useRef();
  const popperRef = useRef();
  const arrowRef = useRef();

  const {
    styles: { popper: popperStyle, arrow: arrowStyle },
    attributes: { popper: popperAttributes }
  } = usePopper(referenceRef, popperRef, {
    modifiers: [
      { name: "offset", options: { offset: [0, 8] } },
      { name: "arrow", options: { element: arrowRef.current } }
    ]
  });
```

so that we keep the same API of Popper 2

**Comment by atomiks** [comment]
@FezVrasta that would also work cleanly with Virtual Elements which don't work with the previous hook! Great solution.

For the arrow ref problem, a callback ref works, but it's not exactly consistent or pretty: https://codesandbox.io/s/optimistic-sea-rgqku

The hook also runs the second `useLayoutEffect` on first update needlessly, and the arrow needs to be updated as well. So that's 3 updates – but if we use a condition it can be reduced to 2 with this method.

**Comment by renke** [comment]
A few API suggestions (based on my own hook version of popper.js):

```js
// optional, true by default, enables or disables popper.js entirely
const enabled = true;

// optional, [] by default, update popper based on other props being changed
const dependencies = [someDataThatChangesPopperPosition]

// optional, partial, default options should be exported by popper though
const popperOptions = {
// ...
}

// order of parameters could be changed or "named" parameters could be used instead, of course
const {popperProps, arrowProps, popperInstance} = usePropper(referenceRef, popperRef, enabled, dependencies, popperOptions)
```

In addition to that, it might make sense to expose a low-level hook (default config, no popper/arrow props) and high-level hook (which uses the low-level one and behaves like the current component based variant).

**Comment by ignatevdev** [comment]
Hooks are cool, but I don't quite understand how you would handle the actual popper change or unmount.

If you are connecting to the components using ref, it is not possible to run a `useEffect` hook on the ref change, which means that this model kinda falls apart.

In my opinion it's better to simply update the library to the latest popper and keep the API the same. It works well and does the job, but the lack of features which were introduced with popper@2, such is auto placement is really annoying. Not everything has to be rewritten with hooks, or at least not on the public level. Using hooks for some internal code might still be ok.

**Comment by JKillian** [comment]
Great discussions! I was curious if there's a WIP branch or anything demonstrating the new API? I'm considering switching my codebase over from Tether -> Popper, I'd just rather wait to do it until the hooks API is released so that we don't have to make another transition later.

**Comment by jquense** [comment]
if anyone is looking for some public implementation  react-overlays has a popper hook: https://github.com/react-bootstrap/react-overlays/blob/master/src/usePopper.js

**Comment by designbyadrian** [comment]
This looks much more convoluted than the Manager/Reference/Popper structure of 1.2 – what is there to gain?

**Comment by ignatevdev** [comment]
@jquense I was trying to make my own hook the same way you did, but I got really confused if I should try to prevent unnecessary state changes.

Modifiers are run on every scroll event, which would trigger dozens of `setState` calls. In theory, this can result in a performance issue if someone tries to put an unoptimized component inside the dropdown, and I'm not sure if I should try to debounce it in my component.

Maybe someone has already thought about it, but it seems like every popper adapter for react just doesn't care about it.

Great hook otherwise, I might be stealing some code from it 🤓

**Comment by jquense** [comment]
I don't think you need to worry about it unless you are running into perf issues. Popper already schedules and dedupes the events via requestAnimationFrame so it should be smooth even if it's noisy. If it does causes issues you can disable updates from events, which is partly why its a first class option on the hook

**Comment by ignatevdev** [comment]
Alright, thanks!

I have also tested your hook implementation and would like to share a few suggestions, because they might be relevant to anyone who tries to do the same and also relevant to the issue.

1. Passing elements instead of refs might cause issues on the initial mount and further remount of the child component

In my case, because refs are created before the component mounts, the initial `useEffect` call was receiving `null` for both reference and popper elements. And because when ref is saved its value is mutated, it doesn't really matter if you put them as a dependency to `useEffect`, it most likely won't be triggered. However, if you switch arguments to refs and get the element instances inside the hook - the initial mount would receive the elements. 

2. The first approach fixes the initial mount problem, but it account for the ref updates. If for some reason react recreates the popper element during the component lifecycle, the initial ref value would point to an already unmounted element and `useEffect` will not detect the change. This will cause popper to behave incorrectly and can't be left as is.

To fix that, the best way is to accept only the reference element ref as an argument and create the popper ref inside the hook as a function. This would change the api, but not as much.

This [is already done](https://github.com/popperjs/react-popper/blob/master/src/Popper.js#L76) in the current version of `react-popper`, but inside the class component.
For me it looks something like this:

```
const saveRef = (el: HTMLElement) => {
    if (!el || el === popperElementRef.current) return;

    popperElementRef.current = el;

    destroyPopper();

    initPopper();
};
```

And it seems to me that this is the only way to actually support the full lifecycle of the popper component and react to the ref changes and every hook implementation should take this into account.

**Comment by BenGladman** [comment]
I have just implemented a hooks api closely based on the one in react-overlays mentioned above. I came across the problems mentioned by @ignatevdev . To solve, used the same technique used in react-overlays, which is instead of using `useRef` to hold the elements, use `useState`. Like this:

```
  const [referenceEl, setReferenceEl] = useState<HTMLElement | null>(null);
  const [contentEl, setContentEl] = useState<HTMLElement | null>(null);

  const { styles, arrowStyles, placement } = usePopper(
    referenceEl,
    contentEl,
    options
  );

  return (
    <>
      <Reference ref={setReferenceEl} />
      {show &&
        createPortal(
          <Content
            ref={setContentEl}
            style={styles}
            placement={placement}
          />,
          document.body
        )}
    </>
  );
```

**Comment by Velenir** [comment]
I would like to add another `usePopper` example implementation
https://codesandbox.io/s/react-popper-hook-2z49d
Two variants: DumbExample -- where popper takes care of styling, and SmartExample -- react handles styling.

I hope it will be of use for someone.

**Comment by ignatevdev** [comment]
@BenGladman 

I have also tried that approach, actually, but in my case it was causing infinite loop, which is why I ended up using refs. Maybe there is something wrong with how I render the actual popper, but I didn't dive too much into it because I was migrating the working code from `react-popper` and wanted to achieve the same behaviour. But if it works for you without a problem, I guess it is an option.

**Comment by jquense** [comment]
To clarify folks, out hook does not accept refs **intentionally** because `useRef` is the wrong thing to use when you need to be updated when they change. Instead you should use a "callback ref" (react's confusing name not mine). 

```js
const [el, setEl] = useState<HTMLElement>(null)
const popper = usePopper(el)

return <div ref={setEl} />
```

As @ignatevdev noted the problem with refs is you cannot respond to changes very easily. instead In other words, `useState` is the more correct thing to do here if you need to respond to element changes like we do. That it is `null` on the first pass is unimportant in practice (in our experience here, and in react-bootstrap. b/c the element is set and updated before any DOM rendering issues could happen.

references:
https://reactjs.org/docs/refs-and-the-dom.html#callback-refs
https://twitter.com/sebmarkbage/status/1091808948523581440

**Comment by BenGladman** [comment]
> it's fine to call set state in render

Nice, thanks for the docs link, that has put my mind at ease!

**Comment by FezVrasta** [comment]
Here's a PR with a first draft of the `usePopper` Hook: https://github.com/popperjs/react-popper/pull/343

I'd also like to rewrite the existing render-props components to use the new Hook internally, but I'll wait for some feedback on the newly proposed Hook before I proceed.

**Comment by punkpeye** [comment]
How does one combine `useRef` and `useState`?

```ts
const [el, setEl] = useState<HTMLElement>(null)
const popper = usePopper(el)

return <div ref={setEl} />
```

In this example I also need `useRef` referencing the same element.

**Comment by diondiondion** [comment]
> I think it should be:

That should work. You can also assign the ref right in the callback:

```jsx
return (
  <div
    ref={el => {
      setEl(el);
      ref.current = el;
    }}
  />
);
```
