### ISSUE TITLE
Any idea when you'll move to Popper.js 2.0?

### ISSUE THREAD

**Issue by tylergraf** [popperjs/react-popper#328]
Just wondering. There's a bug in popper 1 with backup placement and I hear it's fixed in 2.0.

**Comment by FezVrasta** [comment]
There is some conversation about it on #241

**Comment by ryanelian** [comment]
![image](https://user-images.githubusercontent.com/8892187/73120324-02f23880-3f9f-11ea-9237-19e1866d7bb5.png)

Ok this sucks. Apparently reactstrap depends on react-popper which depends on popper.js 1x package WHICH is deprecated and causing CI build failing due to deprecation warning in ALL my repositories.

Can we immediately switch to popper.js 2, like very urgently or undeprecate the latest version of popper.js please? 😢

**Comment by FezVrasta** [comment]
Why does your build fail because of a warning?

**Comment by ryanelian** [comment]
![image](https://user-images.githubusercontent.com/8892187/73120550-32567480-3fa2-11ea-84b5-78397ea0852d.png)

Using GitHub Action. It fails on warning apparently?

**Comment by FezVrasta** [comment]
You should probably tell Yarn to not throw warnings

**Comment by ryanelian** [comment]
I would love to do that but that's not possible at all.

https://legacy.yarnpkg.com/en/docs/cli/install

https://github.com/yarnpkg/yarn/issues/6672

**Comment by FezVrasta** [comment]
You can create a `.yarnrc` file and put this in there:
```
loglevel error
```
