### ISSUE TITLE
Update Popper.js to version 2

### ISSUE THREAD

**Issue by sgrishchenko** [popperjs/react-popper#332]
Second version of Popper.js was published and it would be nice to support it.

**Comment by colepeters** [comment]
Duplicate of #328, see discussion in #241 :)

**Comment by FezVrasta** [comment]
`react-popper@2.0.0` is now on npm, it supports Popper 2, but it doesn't provide a React Hooks based API for the moment.

I bumped the minimum React version to 16.8 in order to get rid of `create-react-context` and to make it possible to release a `feature` version with a new Hooks based API in the future without having to cut a new major.

Please report any problems with it by filing new issues.
