### ISSUE TITLE
Provide a more approachable example

### ISSUE THREAD

**Issue by atomicpages** [popperjs/react-popper#340]
First and foremost, thanks for the great work on `react-popper` and popper.js 2! 

I checked out the demo for example usage, but it was a little challenging to understand. It would be nice to have "bite-sized" examples for those who are new to popper.js and/or React. I created a codesandbox example that contains five examples that are more approachable and demonstrate usage in a pragmatic fashion: https://codesandbox.io/s/brave-lumiere-frgbe

Happy to submit a PR for this on the README; however, it might make more sense to have an official popper.js CSB 😄

**Comment by FezVrasta** [comment]
Thanks for the examples.

I think it would make sense to provide a React alternative to https://popper.js.org/docs/v2/tutorial/, I'd love to have it in the popper.js.org website, so that we can keep all the documentation in a single place.

If you'd like to convert the existing vanilla js tutorial into a react-popper one please do so by submitting a PR in the popper-core repository.

**Comment by atomicpages** [comment]
@FezVrasta sure I'd be happy to do that.
